name: Bug反馈
description: 报告在浏览网站中遇到的问题。
title: "[Bug]: "
labels: ["类型:bug"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - QingFeng-awa
body:
  - type: markdown
    attributes:
      value: |
        感谢您愿意花费时间来提出issue。<br>
        在此之前,请您确认:
        - 这不是因为您的环境(例如使用的是IE浏览器)而导致的问题。
        - 没有与此主要问题相同的issue。
  - type: input
    id: Email
    attributes:
      label: 联系方式(邮箱)
      description: 接受市面上大部分的邮箱,我们推荐您使用@163.com/@qq.com。您可以选择不填。
    validations:
      required: false
  - type: textarea
    id: maybe
    attributes:
      label: 期望的正确结果是?
      description: 您认为该正常出现什么?
    validations:
      required: true
  - type: textarea
    id: but
    attributes:
      label: 实际的输出结果是?
      description: 实际上出现了什么?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 您使用的浏览器是?
      description: IE用户就不要反馈issue了。
      multiple: false
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: 相关日志输出
      description: 请复制并粘贴任何相关的日志输出(例如网站显示的报错),这将自动格式化为代码,因此无需反引导。
      render: shell
  - type: textarea
    id: other
    attributes:
      label: 其它信息
    validations:
      required: false
